---
kind: pipeline
type: docker
name: nvchecker
steps:
- name: nvchecker
  image: python:3.10.0-alpine
  commands:
  - apk add curl-dev g++ bash jq curl
  - python -m pip install --upgrade pip
  - pip install nvchecker[pypi] giteapy
  - ./nvchecker.sh
  environment:
    GITEA_BOT_TOKEN:
      from_secret: GITEA_BOT_TOKEN
    NVCHECKER_GITHUB_TOKEN:
      from_secret: NVCHECKER_GITHUB_TOKEN
  when:
    event:
    - cron
    - custom

---
kind: pipeline
type: docker
name: aur-syncer
steps:
- name: sync to github
  image: appleboy/drone-git-push
  settings:
    remote: git@github.com:imlonghao/aur.git
    remote_name: github
    branch: master
    local_ref: master
    force: "true"
    ssh_key:
      from_secret: GITHUB_DEPLOY_SSH_KEY
  when:
    event:
    - push
- name: sync-to-aur
  image: archlinux
  commands:
  - pacman -Sy
  - pacman -S --noconfirm git openssh sudo binutils
  - echo $SSH_KEY | base64 -d > /tmp/id_rsa
  - chmod 0600 /tmp/id_rsa
  - GIT_SSH_COMMAND="ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./sync.sh
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  when:
    event:
    - push
- name: auto-close-issue
  image: python:3.10.0-slim-bullseye
  commands:
  - python -m pip install --upgrade pip packaging
  - pip install giteapy
  - python autoclose.py
  environment:
    GITEA_BOT_TOKEN:
      from_secret: GITEA_BOT_TOKEN
  when:
    event:
    - push
