stages:
  - nvchecker

nvchecker:
  image: python:3.8-alpine
  stage: nvchecker
  script: |
    apk add curl-dev
    python -m pip install --upgrade pip
    pip install nvchecker python-gitlab
    ./nvchecker.sh
  only:
    variables:
      - $NVCHECKER
