stages:
  - nvchecker
  - sync

nvchecker:
  image: python:3.8-alpine
  stage: nvchecker
  script: |
    apk add curl-dev g++ bash
    python -m pip install --upgrade pip
    pip install nvchecker python-gitlab
    ./nvchecker.sh
  only:
    variables:
      - $NVCHECKER

sync:
  image: alpine
  stage: sync
  script: |
    apk add bash git
    GIT_SSH_COMMAND="ssh -i $id_25519 -o StrictHostKeyChecking=no" ./sync.sh
  only:
    refs:
      - master
