stages:
  - nvchecker

nvchecker:
  image: python:3.8-alpine
  stage: nvchecker
  script: |
    apt update && apt install -y libcurl4-openssl-dev
    python -m pip install --upgrade pip
    pip install nvchecker python-gitlab
    ./nvchecker.sh
  only:
    variables:
      - $NVCHECKER
