name: Deploy to AUR

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: aur.archlinux.org
      - name: Generate .SRCINFO
        uses: https://github.com/imlonghao/generate-srcinfo@v0.1.2
      - name: Sync to AUR
        run: ./sync.sh
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install packaging giteapy
      - name: Close issue
        run: python autoclose.py
        env:
          GITEA_BOT_TOKEN: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
