name: New Version Checker

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nvchecker PyGithub
      - name: nvchecker
        run: ./nvchecker.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVCHECKER_GITHUB_TOKEN: ${{ secrets.NVCHECKER_GITHUB_TOKEN }}
